name: Publish Notion website to GitHub Pages

on:
  # Manual update only.
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout loconotion
        uses: actions/checkout@v3
        with:
          repository: tetracionist/loconotion
          path: loconotion
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: pages_repo
      - name: Install Specific Chrome Version
        run: |
          # Add Google Chrome repository
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          # Install a specific version of Chrome
          sudo apt-get install -y google-chrome-stable=114.0.5735.90-1
          google-chrome --version

      - name: Install Matching ChromeDriver
        run: |
          # Download ChromeDriver for Chrome 114
          wget -N "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version
      - name: Install Loconotion dependencies
        run: pip install -r loconotion/requirements.txt
      - name: Run Loconotion
        run: |
          python3 loconotion/loconotion --chromedriver chromedriver "pages_repo/site.toml"
      - name: Push to GitHub pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_DEPLOY_DIR=../dist/site \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo
