name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Loconotion Repo
        uses: actions/checkout@v3
        with:
          repository: tetracionist/loconotion
          path: loconotion

      - name: Checkout Project Repo
        uses: actions/checkout@v3
        with:
          path: pages_repo

      - name: Install Dependencies
        run: pip install -r loconotion/requirements.txt

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          CHROMIUM_VERSION=$(chromium-browser --version | cut -d ' ' -f 2)
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.2/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/
          chromedriver --version

      - name: Run Loconotion
        run: |
          export CHROME_BIN=/usr/bin/chromium-browser
          export PATH=$PATH:/usr/bin
          echo "====================== PINTINHO =================="
          ls loconotion/loconotion
          mkdir -p loconotion/loconotion/dist/site/seja-bem-vindo-17b6b3d4ad6880e3b3d4d38904a2bcb8notion.site
          touch loconotion/loconotion/dist/site/seja-bem-vindo-17b6b3d4ad6880e3b3d4d38904a2bcb8notion.site/seja-bem-vindo.html
          python3 loconotion/loconotion --chromedriver /usr/bin/chromedriver "pages_repo/site.toml"

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_DEPLOY_DIR=../dist/site \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo
