name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Loconotion Repo
        uses: actions/checkout@v3
        with:
          repository: tetracionist/loconotion
          path: loconotion

      - name: Checkout Project Repo
        uses: actions/checkout@v3
        with:
          path: pages_repo

      - name: Install Dependencies
        run: pip install -r loconotion/requirements.txt

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          CHROMIUM_VERSION=$(chromium-browser --version | cut -d ' ' -f 2)
          wget https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.0/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          ls /usr/bin/
          ls
          sudo mv chromedriver /usr/bin/
          chromedriver --version

      - name: Run Loconotion
        run: |
          export CHROME_BIN=/usr/bin/chromium-browser
          export PATH=$PATH:/usr/bin
          python3 loconotion/loconotion --chromedriver /usr/bin/chromedriver "pages_repo/site.toml"

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_DEPLOY_DIR=../dist/site \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo
