name: Publish Notion website to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout loconotion
        uses: actions/checkout@v3
        with:
          repository: tetracionist/loconotion
          path: loconotion

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: pages_repo

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Verifica as versões
          chromium-browser --version
          chromedriver --version
          # Remove o chromedriver antigo se necessário
          sudo rm /usr/bin/chromedriver
          # Baixar a versão compatível do chromedriver
          CHROMIUM_VERSION=$(chromium-browser --version | cut -d ' ' -f 2 | cut -d '.' -f 1,2)
          CHROMEDRIVER_VERSION=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROMIUM_VERSION})
          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/
          chromedriver --version

      - name: Install Loconotion dependencies
        run: pip install -r loconotion/requirements.txt

      - name: Run Loconotion
        run: |
          # Definindo o caminho correto do binário do Chromium
          export CHROME_BIN=/usr/bin/chromium-browser
          # Garantir que o chromedriver está no caminho correto
          export PATH=$PATH:/usr/bin
          python3 loconotion/loconotion --chromedriver /usr/bin/chromedriver "pages_repo/site.toml"

      - name: Push to GitHub pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          GIT_DEPLOY_DIR=../dist/site \
          GIT_DEPLOY_BRANCH=gh-pages \
          GIT_DEPLOY_REPO="https://${{ github.token }}@github.com/${{ github.repository }}.git" ./deploy.sh
        working-directory: pages_repo
