name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Loconotion Repo
        uses: actions/checkout@v3
        with:
          repository: tetracionist/loconotion
          path: loconotion

      - name: Checkout Project Repo
        uses: actions/checkout@v3
        with:
          path: pages_repo

      - name: Install Dependencies
        run: pip install -r loconotion/requirements.txt

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          CHROMIUM_VERSION=$(chromium-browser --version | cut -d ' ' -f 2)
          wget https://chromedriver.storage.googleapis.com/${CHROMIUM_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/
          chromedriver --version

      - name: Run Loconotion
        run: |
          export CHROME_BIN=/usr/bin/chromium-browse
